language: r
env:
  - CODECOV_TOKEN="88e7fdc4-b2fb-4262-ae46-a02683f753d2"
r:
  - oldrel
  - release
  - devel
before_install:
  - sudo apt install -y libsodium-dev
install:
  - Rscript -e 'install.packages("devtools", repos = "https://cran.rstudio.com")'
  - Rscript -e 'devtools::install_dev_deps()'
  - Rscript -e 'remotes::install_cran("covr")'
script:
  - R CMD build .
  - R CMD check --as-cran *.tar.gz
  - cat REDCapExporter.Rcheck/00check.log
after_success:
  - Rscript -e 'covr::codecov(type = c("tests", "examples"), commentDontrun = FALSE, commentDonttest = FALSE)'
