language: r
r:
  - oldrel
  - release
  - devel
install:
  - Rscript -e 'install.packages("devtools", repos = "https://cran.rstudio.com")'
script:
  - R CMD build .
  - R CMD check --as-cran *.tar.gz
