language: r
r:
  - oldrel
  - release
  - devel
install:
  - Rscript -e 'install.packages("devtools", repos = "https://cran.rstudio.com")'
script:
  - touch data/avs_raw_metadata.rda
  - touch data/avs_raw_project_info.rda
  - touch data/avs_raw_record.rda
  - touch data/avs_raw_user.rda
  - make check-as-cran
