# avs-export.R
#
# expected working directory is the project root
#
# Purpose: extract example REDCap data via the REDCap API and save the data in
# the package for use in examples and vignettes.
#
# library(secret)
# Sys.setenv(USER_KEY = "~/.ssh/vaults")
source("./R/export_redcap_project.R")
source("./R/keyring.R")

REDCapExporter_keyring_check()
REDCapExporter_add_api_token("2000_2001_Avalanche")
REDCapExporter_get_api_token("2000_2001_Avalanche")

Sys.setenv(REDCap_API_URI = "https://redcap.ucdenver.edu/api/")
Sys.setenv(REDCap_API_TOKEN = REDCapExporter_get_api_token("2000_2001_Avalanche"))

avs_raw_project_info <- export_content(content = "project",  format = "csv")
avs_raw_metadata     <- export_content(content = "metadata", format = "csv")
avs_raw_user         <- export_content(content = "user",     format = "csv")
avs_raw_record       <- export_content(content = "record",   format = "csv")
avs_raw_core         <- export_core(format = "csv")

save(avs_raw_project_info, file = "./data/avs_raw_project_info.rda")
save(avs_raw_metadata,     file = "./data/avs_raw_metadata.rda")
save(avs_raw_user,         file = "./data/avs_raw_user.rda")
save(avs_raw_record,       file = "./data/avs_raw_record.rda")
save(avs_raw_core,         file = "./data/avs_raw_core.rda")

cat("# do not edit this file by hand, edit data-raw/avs-exports.R",
    "#' Raw Exports From an Example REDCap Project",
    "#'",
    "#' These data sets are the results of calling \\code{\\link{export_content}}.  An API token is required to reproduce these calls. No such token will be provided publicly, so these data sets are provided so end users can run examples for other tools provided in the REDCapExporter package.",
    "#'",
    "#' \\code{avs_raw_project_info} provides meta data about the project itself.",
    "#'",
    "#' \\code{avs_raw_metadata} is the data dictionary for the REDCap Project.  This information can be used with \\code{\\link{format_record}} to build a \\code{data.frame} that is ready for analysis.",
    "#'",
    "#' \\code{avs_raw_user} REDCap Project user table.",
    "#'",
    "#' \\code{avs_raw_record} REDCap Project records, i.e., 'the data.'",
    "#'",
    "#' @examples",
    "#' \\dontrun{",
    "#' avs_raw_project_info <- export_content(content = \"project\",  format = \"csv\")",
    "#' avs_raw_metadata     <- export_content(content = \"metadata\", format = \"csv\")",
    "#' avs_raw_user         <- export_content(content = \"user\",     format = \"csv\")",
    "#' avs_raw_record       <- export_content(content = \"record\",   format = \"csv\")",
    "#' avs_raw_core         <- export_core(format = \"csv\")",
    "#' }",
    "#'",
    "#' data(avs_raw_project_info)",
    "#' data(avs_raw_user)",
    "#' data(avs_raw_metadata)",
    "#' data(avs_raw_record)",
    "#' data(avs_raw_core)",
    "#'",
    "#' str(avs_raw_project_info)",
    "#' str(avs_raw_user)",
    "#' str(avs_raw_metadata)",
    "#' str(avs_raw_record)",
    "#' str(avs_raw_core)",
    "#'",
    "#' avs <- format_record(avs_raw_record, avs_raw_metadata)",
    "#' str(avs)",
    "#'",
    "#'",
    "#' @name example_data",
    "NULL",
    "",
    "#' @rdname example_data",
    "\"avs_raw_project_info\"",
    "",
    "#' @rdname example_data",
    "\"avs_raw_metadata\"",
    "",
    "#' @rdname example_data",
    "\"avs_raw_user\"",
    "",
    "#' @rdname example_data",
    "\"avs_raw_record\"",
    "",
    "#' @rdname example_data",
    "\"avs_raw_core\"",
    sep = "\n",
    file = "./R/datasets.R"
    )


