on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        R: [ '3.5.3', '3.6.1' ]
    name: R ${{ matrix.R }} sample
    steps:
      - uses: actions/checkout@master
      - name: System Dependencies
        run: sudo apt install -y libcurl4-openssl-dev libsodium-dev texlive-latex-base texlive-fonts-recommended texlive-fonts-extra pandoc pandoc-citeproc
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - name: Install Dependencies
        run: |
          Rscript -e "install.packages('remotes', repo = 'https://cran.rstudio.com')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: R CMD build
        run: R CMD build .
      - name: R CMD check
        run: R CMD check --as-cran *.tar.gz
